// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbljwlbqmgaivwryxicg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibGp3bGJxbWdhaXZ3cnl4aWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMDkwMzMsImV4cCI6MjA1Mjg4NTAzM30.Dh4m8ouzMT_DihUeMpa9lRkzv8mK9j0ze-My4Slwzdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);